DATA:
  data_root: #DATAS PARENT FOLDER
  output_name: #OUTPUT NAME
  save_dir: #OUTPUT FOLDER
  half_precision: 1
  img_size: "640x480"

NETWORK:
  nb_class: 20
  ptnet_feat: 61

TRAIN:
  lr: 0.00006
  momentum: 0.9
  weight_decay: 0.00005
  batch_size: 8
  epoch_number: 100
  print_rate: 1000
  save_rate: 1
  div_rate: 0
  div_factor: 0.5
  gpu: ["0"]                                                       #ONLY MANAGE MONO GPU FOR NOW
  train_file: #PATH TO THE TRAIN LIST FILES
  eval_file:  #PATH TO THE VAL LIST FILES
  num_workers: 0
  ignore_label: 255
  img_size: [640, 480]
  checkpoint: "" #PATH TO THE CHECKPOINT TO RESUME TRAINING IF ANY

EVAL:
  batch_size: 8
  print_rate: 200
  gpu: ["0"]
  test_file: #PATH TO THE TEST LIST FILES
  num_workers: 0
  ignore_label: 255
  img_size: [640, 480]
  checkpoint: #PATH TO THE CHECKPOINT TO RESUME TRAINING IF ANY


TEST:
  batch_size: 8
  print_rate: 200
  gpu: ["0"]
  test_file: #PATH TO THE TEST LIST FILES
  num_workers: 0
  ignore_label: 255
  img_size: [640, 480]
